-- grupos_categoria
insert into public.grupos_categoria (id, nome, cor_clara, cor_escura, ordem) values
  (1, 'Moradia', '#a65f00', '#bd7400', 1),
  (2, 'Alimentação', '#008d59', '#00a36d', 2),
  (3, 'Transporte', '#af4387', '#c6589c', 3),
  (4, 'Saúde', '#2171cc', '#3986e4', 4),
  (5, 'Lazer', '#677d00', '#7b9300', 5),
  (6, 'Assinaturas', '#8156c0', '#966cd7', 6),
  (7, 'Compras', '#0087a4', '#009dbb', 7),
  (8, 'Outros', '#bd4334', '#d55948', 8);

-- categorias
insert into public.categorias (nome, grupo_id, fluxo_especial) values
  ('Moradia', 1, null),
  ('Energia', 1, null),
  ('Internet e Telefonia', 6, null),
  ('Streaming e Assinaturas', 6, null),
  ('Contas e Assinaturas', 6, null),
  ('Mercado', 2, null),
  ('Restaurante', 2, null),
  ('Padaria', 2, null),
  ('Combustível', 3, null),
  ('Transporte por app', 3, null),
  ('Farmácia', 4, null),
  ('Plano de Saúde', 4, null),
  ('Academia', 4, null),
  ('Cinema e Lazer', 5, null),
  ('Presentes', 5, null),
  ('Esporte', 5, null),
  ('Eletrodomésticos', 7, null),
  ('Compras diversas', 7, null),
  ('Pet', 8, null),
  ('Serviços domésticos', 8, null),
  ('Seguros', 8, null),
  ('Tarifas bancárias', 8, null),
  ('Saque', 8, null),
  ('Educação e Cultura', 8, null),
  ('Pix enviado', 8, null),
  ('Outros', 8, null),
  ('Salário', 8, null),
  ('Receita (Pix recebido)', 8, null),
  ('Rendimentos', 8, null),
  ('Investimentos', 8, 'investimento'),
  ('Pagamento de Fatura', 8, 'transferencia');

-- contas
insert into public.contas (nome, tipo) values
  ('Conta corrente', 'conta_corrente'),
  ('Cartão de crédito', 'cartao_credito'),
  ('Dinheiro', 'dinheiro');

-- lancamentos (dados de exemplo: julho/2026)
insert into public.lancamentos (data, descricao, valor, categoria_id, conta_id, origem, mcc, tipo_lancamento) values
  ('2026-07-01', 'IFOOD *RESTAURANTE MASSA NOSTRA', -68.9, (select id from public.categorias where nome = 'Restaurante'), (select id from public.contas where nome = 'Cartão de crédito'), 'fatura', '5812', null),
  ('2026-07-02', 'POSTO IPIRANGA JD PAULISTA', -210, (select id from public.categorias where nome = 'Combustível'), (select id from public.contas where nome = 'Cartão de crédito'), 'fatura', '5541', null),
  ('2026-07-02', 'NETFLIX.COM ASSINATURA MENSAL', -44.9, (select id from public.categorias where nome = 'Streaming e Assinaturas'), (select id from public.contas where nome = 'Cartão de crédito'), 'fatura', '4899', null),
  ('2026-07-03', 'DROGARIA SAO PAULO FL 118', -87.45, (select id from public.categorias where nome = 'Farmácia'), (select id from public.contas where nome = 'Cartão de crédito'), 'fatura', '5912', null),
  ('2026-07-04', 'AMAZON BR MARKETPLACE', -156.8, (select id from public.categorias where nome = 'Compras diversas'), (select id from public.contas where nome = 'Cartão de crédito'), 'fatura', '5999', null),
  ('2026-07-05', 'SUPERMERCADO PAO DE ACUCAR 1042', -432.17, (select id from public.categorias where nome = 'Mercado'), (select id from public.contas where nome = 'Cartão de crédito'), 'fatura', '5411', null),
  ('2026-07-07', 'SPOTIFY BR PREMIUM', -21.9, (select id from public.categorias where nome = 'Streaming e Assinaturas'), (select id from public.contas where nome = 'Cartão de crédito'), 'fatura', '5735', null),
  ('2026-07-09', 'UBER *TRIP HELP.UBER.COM', -32.4, (select id from public.categorias where nome = 'Transporte por app'), (select id from public.contas where nome = 'Cartão de crédito'), 'fatura', '4121', null),
  ('2026-07-10', 'OUTBACK STEAKHOUSE MORUMBI', -189.6, (select id from public.categorias where nome = 'Restaurante'), (select id from public.contas where nome = 'Cartão de crédito'), 'fatura', '5812', null),
  ('2026-07-12', 'LIVRARIA CULTURA CONJ NACIONAL', -94, (select id from public.categorias where nome = 'Educação e Cultura'), (select id from public.contas where nome = 'Cartão de crédito'), 'fatura', '5942', null),
  ('2026-07-13', 'UBER *TRIP HELP.UBER.COM', -28.7, (select id from public.categorias where nome = 'Transporte por app'), (select id from public.contas where nome = 'Cartão de crédito'), 'fatura', '4121', null),
  ('2026-07-15', 'MAGAZINE LUIZA PARC 1/3', -133.3, (select id from public.categorias where nome = 'Eletrodomésticos'), (select id from public.contas where nome = 'Cartão de crédito'), 'fatura', '5722', null),
  ('2026-07-16', 'PADARIA BELLA MASSA', -46.2, (select id from public.categorias where nome = 'Padaria'), (select id from public.contas where nome = 'Cartão de crédito'), 'fatura', '5462', null),
  ('2026-07-18', 'POSTO SHELL SELECT PINHEIROS', -195, (select id from public.categorias where nome = 'Combustível'), (select id from public.contas where nome = 'Cartão de crédito'), 'fatura', '5541', null),
  ('2026-07-20', 'CINEMARK SHOPPING ELDORADO', -78, (select id from public.categorias where nome = 'Cinema e Lazer'), (select id from public.contas where nome = 'Cartão de crédito'), 'fatura', '7832', null),
  ('2026-07-21', 'SUPERMERCADO EXTRA HIPER 305', -288.55, (select id from public.categorias where nome = 'Mercado'), (select id from public.contas where nome = 'Cartão de crédito'), 'fatura', '5411', null),
  ('2026-07-23', 'FARMACIA PAGUE MENOS 0871', -62.3, (select id from public.categorias where nome = 'Farmácia'), (select id from public.contas where nome = 'Cartão de crédito'), 'fatura', '5912', null),
  ('2026-07-24', 'APPLE.COM/BILL ICLOUD', -9.9, (select id from public.categorias where nome = 'Streaming e Assinaturas'), (select id from public.contas where nome = 'Cartão de crédito'), 'fatura', '5735', null),
  ('2026-07-26', 'IFOOD *LANCHONETE DO ZE', -54.8, (select id from public.categorias where nome = 'Restaurante'), (select id from public.contas where nome = 'Cartão de crédito'), 'fatura', '5812', null),
  ('2026-07-27', 'DECATHLON MORUMBI', -219.9, (select id from public.categorias where nome = 'Esporte'), (select id from public.contas where nome = 'Cartão de crédito'), 'fatura', '5655', null),
  ('2026-07-01', 'PIX IMOB SANTA CLARA - ALUGUEL JUL/26', -2300, (select id from public.categorias where nome = 'Moradia'), (select id from public.contas where nome = 'Conta corrente'), 'extrato', null, 'PIX ENVIADO'),
  ('2026-07-02', 'DEB AUT CONDOMINIO EDIF AURORA', -480, (select id from public.categorias where nome = 'Moradia'), (select id from public.contas where nome = 'Conta corrente'), 'extrato', null, 'DEB AUTOMATICO'),
  ('2026-07-03', 'DEB AUT VIVO FIBRA INTERNET 300MB', -129.9, (select id from public.categorias where nome = 'Internet e Telefonia'), (select id from public.contas where nome = 'Conta corrente'), 'extrato', null, 'DEB AUTOMATICO'),
  ('2026-07-05', 'CREDITO SALARIO - NOVA MIDIA LTDA', 8450, (select id from public.categorias where nome = 'Salário'), (select id from public.contas where nome = 'Conta corrente'), 'extrato', null, 'CREDITO TED'),
  ('2026-07-06', 'DEB AUT ENEL DISTRIBUICAO ENERGIA', -187.42, (select id from public.categorias where nome = 'Energia'), (select id from public.contas where nome = 'Conta corrente'), 'extrato', null, 'DEB AUTOMATICO'),
  ('2026-07-07', 'COMPRA DEBITO SUPERMERCADO DIA', -142.88, (select id from public.categorias where nome = 'Mercado'), (select id from public.contas where nome = 'Conta corrente'), 'extrato', null, 'COMPRA DEBITO'),
  ('2026-07-08', 'PAGTO FATURA CARTAO FINAL 4417', -2187.43, (select id from public.categorias where nome = 'Pagamento de Fatura'), (select id from public.contas where nome = 'Conta corrente'), 'extrato', null, 'PAGTO FATURA'),
  ('2026-07-10', 'DEB AUT SMARTFIT ACADEMIA', -119.9, (select id from public.categorias where nome = 'Academia'), (select id from public.contas where nome = 'Conta corrente'), 'extrato', null, 'DEB AUTOMATICO'),
  ('2026-07-11', 'SAQUE TERMINAL 24H AG 0412', -200, (select id from public.categorias where nome = 'Saque'), (select id from public.contas where nome = 'Conta corrente'), 'extrato', null, 'SAQUE'),
  ('2026-07-14', 'PIX CULTURA INGLESA - MENSALIDADE', -420, (select id from public.categorias where nome = 'Educação e Cultura'), (select id from public.contas where nome = 'Conta corrente'), 'extrato', null, 'PIX ENVIADO'),
  ('2026-07-15', 'COMPRA DEBITO POSTO IPIRANGA', -160, (select id from public.categorias where nome = 'Combustível'), (select id from public.contas where nome = 'Conta corrente'), 'extrato', null, 'COMPRA DEBITO'),
  ('2026-07-17', 'DEB AUT UNIMED PLANO DE SAUDE', -689, (select id from public.categorias where nome = 'Plano de Saúde'), (select id from public.contas where nome = 'Conta corrente'), 'extrato', null, 'DEB AUTOMATICO'),
  ('2026-07-18', 'PIX RECEBIDO ESTUDIO ORBITA', 1200, (select id from public.categorias where nome = 'Receita (Pix recebido)'), (select id from public.contas where nome = 'Conta corrente'), 'extrato', null, 'PIX RECEBIDO'),
  ('2026-07-20', 'COMPRA DEBITO DROGASIL FL 221', -73.5, (select id from public.categorias where nome = 'Farmácia'), (select id from public.contas where nome = 'Conta corrente'), 'extrato', null, 'COMPRA DEBITO'),
  ('2026-07-22', 'PIX CLEUSA M SANTOS - DIARISTA', -180, (select id from public.categorias where nome = 'Serviços domésticos'), (select id from public.contas where nome = 'Conta corrente'), 'extrato', null, 'PIX ENVIADO'),
  ('2026-07-24', 'DEB AUT PORTO SEGURO - SEG AUTO', -245.6, (select id from public.categorias where nome = 'Seguros'), (select id from public.contas where nome = 'Conta corrente'), 'extrato', null, 'DEB AUTOMATICO'),
  ('2026-07-25', 'COMPRA DEBITO PET SHOP AMIGO FIEL', -134, (select id from public.categorias where nome = 'Pet'), (select id from public.contas where nome = 'Conta corrente'), 'extrato', null, 'COMPRA DEBITO'),
  ('2026-07-28', 'PIX RENATA C RIBEIRO - PRESENTE', -150, (select id from public.categorias where nome = 'Presentes'), (select id from public.contas where nome = 'Conta corrente'), 'extrato', null, 'PIX ENVIADO'),
  ('2026-07-29', 'TARIFA PACOTE DE SERVICOS CONTA FACIL', -34.9, (select id from public.categorias where nome = 'Tarifas bancárias'), (select id from public.contas where nome = 'Conta corrente'), 'extrato', null, 'TARIFA'),
  ('2026-07-30', 'CREDITO RENDIMENTO CDB LIQUIDEZ DIARIA', 42.18, (select id from public.categorias where nome = 'Rendimentos'), (select id from public.contas where nome = 'Conta corrente'), 'extrato', null, 'RENDIMENTO'),
  ('2026-07-31', 'PIX CONTA INVESTIMENTO - RESERVA', -1000, (select id from public.categorias where nome = 'Investimentos'), (select id from public.contas where nome = 'Conta corrente'), 'extrato', null, 'PIX ENVIADO');
